site_name: tools-flask
dev_addr: 127.0.0.1:9998
repo_name: GitHub
repo_url: https://github.com/eastsunrise/tools-flask/
edit_uri: edit/master/docs
site_author: Kingen
use_directory_urls: false
theme:
  name: mkdocs
  navigation_depth: 6
extra_javascript:
  - js/kingen.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra_css:
  - css/kingen.css
markdown_extensions:
  - extra
  - admonition
  - codehilite
  - legacy_attrs
  - legacy_em
  - meta
  - nl2br
  - sane_lists
  - smarty
  - toc
  - wikilinks
  - mdx_math:
      enable_dollar_delimiter: True
nav:
  - Home: index.md
